---
title: "CRI Model Descriptions"
author: "Nate Breznau"
date: "1/15/2020"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
library(pacman)

# Create a working directory string and a function to call the wd for every code chunk
wd <- "C:/data" #set your wd here
wdir <- function(x){
  paste(wd,x, sep = "/")
}

pacman::p_load("readxl","dplyr","tidyr","knitr","stringr")

```


```{r readspec, include=T}
spec <- read.csv(wdir("xout.csv"), header = T, na.strings=c(""," ","NA"))

# Prep data for tabulation

# List waves
spec$waves <- ifelse(spec$w1985==1,"1985", "")
spec$waves <- ifelse(spec$w1990==1 & spec$w1985==1, paste(spec$waves, ", 1990", sep = ""), ifelse(
  spec$w1990==1, paste(spec$waves, "1990", sep = ""), spec$waves))
spec$waves <- ifelse(spec$w1996==1 & spec$w1990==1, paste(spec$waves, ", 1996", sep = ""), ifelse(
  spec$w1996==1, paste(spec$waves, "1996", sep = ""), spec$waves))
spec$waves <- ifelse(spec$w2006==1 & spec$w1996==1, paste(spec$waves, ", 2006", sep = ""), ifelse(
  spec$w2006==1, paste(spec$waves, "2006", sep = ""), spec$waves))
spec$waves <- ifelse(spec$w2016==1 & spec$w2006==1, paste(spec$waves, ", 2016", sep = ""), ifelse(
  spec$w2016==1, paste(spec$waves, "2016", sep = ""), spec$waves))

# List countries by 2-digit alpha ISO
spec2 <- select(spec, AU:VE, id)
spec <- select(spec, -c(AU:VE))
spec <- rename(spec, numbr_countries = countries)
spec2 <- na_if(spec2, 0)
spec2 <- data.frame(lapply(spec2, as.character), stringsAsFactors=FALSE)
spec2 <- spec2 %>% unite("countries", AU:VE, sep = ", ", na.rm = T, remove = F)

spec <- merge(spec, spec2, by = "id")

# Make a list of independent variables by name, just the main ones
spec3 <- select(spec, main_IV_as_control,socx_ivC:gdp_ivC, id, team)
s3 <- which(spec3=="1",arr.ind=TRUE)
spec3[s3] <- names(spec3)[s3[,"col"]]
spec3 <- na_if(spec3, 0)
spec3 <- data.frame(lapply(spec3, as.character), stringsAsFactors=FALSE)
spec3 <- spec3 %>% unite("main_cntry_vars", main_IV_as_control:gdp_ivC, sep = ", ", na.rm = T, remove = F)
# probably do not need to merge this just use it in the loop





```




```{r genout, include=T}
# Get all team numbers as a list
teams <- unique(spec$team)

for (i in teams){
# Marginal Effects Table
assign(paste0("margin", i), select(subset(spec, i == spec$team), id, DV, main_IV_type, AME, lower, upper))

# Sample
assign(paste0("sample", i), select(subset(spec, i == spec$team), id, waves, countries))


#country level variables
assign(paste0("var_c", i), select(subset(spec3, i == spec3$team), id, main_cntry_vars))
}

```

